In [43]:
import tensorflow as tf
import abc
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import f1_score, accuracy_score
import tensorflow.keras.datasets.reuters as reuters
import tensorflow.keras.activations
import matplotlib.pyplot as plt

class AbstractLayer(tf.keras.layers.Layer):
    """Abstract Layer."""
    
    def __init__(self):
        """Inits the class."""
        super(AbstractLayer, self).__init__()
    
    @abc.abstractmethod
    def call(self, inputs):
        """Makes forward pass of the layer."""
        pass

In [3]:
input = tf.random.uniform(shape=(100, 200, 10))

In [33]:
init_h = tf.zeros(shape=(100, 16, 1))
init_c = tf.random.uniform(shape=(100, 16, 1))

In [38]:
def step(inputs,state):
    print('state zeros',state[0])
    print('state uni',state[1])
    return inputs, state

In [39]:
tf.keras.backend.rnn(step, input, [init_h,init_c])

state zeros tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]], shape=(100, 16, 1), dtype=float32)
state uni tf.Tensor(
[[[0.7511846 ]
  [0.68465996]
  [0.05404115]
  ...
  [0.2860484 ]
  [0.14883041]
  [0.6170641 ]]

 [[0.07102311]
  [0.01869607]
  [0.09202361]
  ...
  [0.17378783]
  [0.49191093]
  [0.20628595]]

 [[0.37108445]
  [0.9388517 ]
  [0.16445291]
  ...
  [0.6830145 ]
  [0.5030799 ]
  [0.27027345]]

 ...

 [[0.3888502 ]
  [0.41658652]
  [0.1384629 ]
  ...
  [0.64316046]
  [0.49896097]
  [0.22663724]]

 [[0.4339651 ]
  [0.05329216]
  [0.06832993]
  ...
  [0.13876116]
  [0.14692426]
  [0.7339083 ]]

 [[0.43748987]
  [0.77171385]
  [0.11022556]
  ...
  [0.7655337 ]
  [0.23948157]
  [0.2594142 ]]], shape=(100, 16, 1),

state zeros tf.Tensor(
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]], shape=(100, 16, 1), dtype=float32)
state uni tf.Tensor(
[[[0.7511846 ]
  [0.68465996]
  [0.05404115]
  ...
  [0.2860484 ]
  [0.14883041]
  [0.6170641 ]]

 [[0.07102311]
  [0.01869607]
  [0.09202361]
  ...
  [0.17378783]
  [0.49191093]
  [0.20628595]]

 [[0.37108445]
  [0.9388517 ]
  [0.16445291]
  ...
  [0.6830145 ]
  [0.5030799 ]
  [0.27027345]]

 ...

 [[0.3888502 ]
  [0.41658652]
  [0.1384629 ]
  ...
  [0.64316046]
  [0.49896097]
  [0.22663724]]

 [[0.4339651 ]
  [0.05329216]
  [0.06832993]
  ...
  [0.13876116]
  [0.14692426]
  [0.7339083 ]]

 [[0.43748987]
  [0.77171385]
  [0.11022556]
  ...
  [0.7655337 ]
  [0.23948157]
  [0.2594142 ]]], shape=(100, 16, 1),

(<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
 array([[5.72921872e-01, 9.91675258e-01, 3.89950633e-01, 9.01983023e-01,
         6.06831193e-01, 4.47578549e-01, 3.18606734e-01, 8.60965610e-01,
         2.27531433e-01, 1.02345705e-01],
        [1.65032029e-01, 1.79419398e-01, 2.31832385e-01, 3.36210132e-01,
         5.68212748e-01, 7.54543662e-01, 6.01867557e-01, 5.94401956e-01,
         1.15191340e-01, 7.82750010e-01],
        [9.51570272e-01, 5.88833809e-01, 1.90635920e-02, 8.73446822e-01,
         9.65607882e-01, 8.95220041e-01, 4.72808480e-01, 5.32623529e-01,
         6.19487405e-01, 9.00191307e-01],
        [7.05989957e-01, 5.31230450e-01, 5.08168817e-01, 6.95856094e-01,
         9.83376980e-01, 4.40087080e-01, 9.59993124e-01, 8.96914840e-01,
         2.05354452e-01, 7.21793294e-01],
        [2.46158004e-01, 7.42158294e-01, 7.09058166e-01, 6.77379608e-01,
         8.26612711e-02, 7.66488671e-01, 6.88934803e-01, 9.46157575e-01,
         1.63383842e-01, 3.02610278e-01],
        

In [968]:
class Custom_LSTM(AbstractLayer):
    
    def __init__(self, hidden_state_size, output_size,): 
        super(Custom_LSTM, self).__init__()
        self.tahn = tensorflow.keras.activations.tanh
        self.softmax = tensorflow.keras.activations.softmax
        self.sigmoid = tensorflow.keras.activations.sigmoid
        
        self.output_size = output_size
        self.hidden_state_size = hidden_state_size
        
        self.point_wise_multi = tf.math.multiply
        self.point_wise_add = tf.math.add
        
    def build(self, input_shape):
        self.concat_size = self.hidden_state_size+input_shape[2]
        i = input_shape[-1]
        self.Whf = self.add_weight(shape=(self.hidden_state_size,self.hidden_state_size),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        self.Whu = self.add_weight(shape=(self.hidden_state_size,self.hidden_state_size),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        self.Whc = self.add_weight(shape=(self.hidden_state_size,self.hidden_state_size),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        self.Who = self.add_weight(shape=(self.hidden_state_size,self.hidden_state_size),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        
        self.Wfx = self.add_weight(shape=(self.hidden_state_size,input_shape[-1]),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        self.Wxu = self.add_weight(shape=(self.hidden_state_size,input_shape[-1]),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        self.Wxc = self.add_weight(shape=(self.hidden_state_size,input_shape[-1]),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        self.Wxo = self.add_weight(shape=(self.hidden_state_size,input_shape[-1]),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        
        self.bf = self.add_weight(shape=(self.hidden_state_size,1),initializer=tf.random_uniform_initializer,trainable=True)
        self.bi = self.add_weight(shape=(self.hidden_state_size,1),initializer=tf.random_uniform_initializer,trainable=True)
        self.bc = self.add_weight(shape=(self.hidden_state_size,1),initializer=tf.random_uniform_initializer,trainable=True)
        self.bo = self.add_weight(shape=(self.hidden_state_size,1),initializer=tf.random_uniform_initializer,trainable=True)
    
        self.Why = self.add_weight(shape=(self.output_size,self.hidden_state_size),
                                      initializer=tf.random_uniform_initializer,
                                      trainable=True)
        self.by = self.add_weight(shape=(self.output_size,1),initializer=tf.random_uniform_initializer,trainable=True)
        pass
           
        
    def step_function(self,inputs,state):
        inputs=tf.reshape(inputs,shape=(-1,inputs.shape[1],1))
        H_state=tf.reshape(state[0],shape=(-1,self.hidden_state_size,1))
        C_state=tf.reshape(state[1],shape=(-1,self.hidden_state_size,1))

        matmul1 = tf.matmul(self.Whf,H_state)
        matmul2 = tf.matmul(self.Wfx,inputs)
        ft=self.sigmoid(tf.matmul(self.Whf,H_state)+tf.matmul(self.Wfx,inputs)+self.bf)
        ut=self.sigmoid(tf.matmul(self.Whu,H_state)+tf.matmul(self.Wxu,inputs)+self.bi)
        cti=self.tahn(tf.matmul(self.Whc,H_state)+tf.matmul(self.Wxc,inputs)+self.bc)
        
        ct=self.point_wise_multi(cti,ut)+self.point_wise_multi(C_state,ft)
        
        ot = self.sigmoid(tf.matmul(self.Who,H_state)+tf.matmul(self.Wxo,inputs)+self.bo)
        new_H_state=self.point_wise_multi(ot,self.tahn(ct))
        new_C_state=ct
        
        print(ct.shape)
        
        output =tf.matmul(self.Why,new_H_state)+self.by
        output = self.softmax(output,axis=1)
        
        
        new_states = [new_H_state,new_C_state]
        print('o',output.shape)
        return output, new_states
   
    
    
    def call(self, inputs):
        """Makes forward pass of the layer."""
        initial_state_h = tf.zeros(shape=[inputs.shape[0],self.hidden_state_size,1])
        initial_state_c = tf.zeros(shape=[inputs.shape[0],self.hidden_state_size,1])
        initial_states = [initial_state_h,initial_state_c]
        last, outputs, states = tf.keras.backend.rnn(self.step_function, inputs, initial_states)
        #print(last)
        last = tf.reshape(last,(-1,self.output_size))
        #print('after',last)
        return last

In [969]:
hidden_state = 10
output_size = 5
batch =6
emb_length= 12
emb_dim = 3

In [970]:
layer = Custom_LSTM(hidden_state, output_size)

In [971]:
init_h = tf.zeros(shape=(batch, hidden_state, 1))
init_c = tf.random.uniform(shape=(batch, hidden_state, 1))
input = tf.random.uniform(shape=(batch,emb_length , emb_dim))
input.shape

TensorShape([6, 12, 3])

In [972]:
layer(input)

(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)
(6, 10, 1)
o (6, 5, 1)


<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[0.20814583, 0.19500268, 0.19184628, 0.20395282, 0.20105237],
       [0.20815718, 0.19494256, 0.19178876, 0.20398054, 0.20113099],
       [0.20842375, 0.1948686 , 0.19187151, 0.2038766 , 0.20095962],
       [0.20808662, 0.19506925, 0.19181654, 0.2039934 , 0.20103428],
       [0.20809287, 0.19494845, 0.19173434, 0.20402625, 0.2011981 ],
       [0.2082244 , 0.19501837, 0.19186392, 0.20393081, 0.20096254]],
      dtype=float32)>

In [907]:
x = tf.random.uniform(shape=(6,30))
y = tf.random.uniform(shape=(30,10))

In [714]:
tf.matmul(x,y)

<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
array([[8.039145 , 8.0225725, 6.304447 , 6.2750196, 7.2234516, 9.551315 ,
        8.009929 , 8.966414 , 5.3220196, 7.4663057],
       [7.902404 , 8.504691 , 6.1970186, 6.089519 , 7.6556435, 8.653246 ,
        8.478404 , 8.871309 , 6.977096 , 7.858895 ],
       [8.064065 , 8.091597 , 6.44348  , 6.7103653, 7.7938704, 8.505557 ,
        8.173331 , 8.416055 , 5.2613173, 7.735242 ],
       [8.836334 , 8.250253 , 6.682113 , 7.334469 , 7.0973525, 9.475395 ,
        8.725254 , 9.335398 , 6.00907  , 8.937771 ],
       [7.612936 , 6.9429955, 6.4827867, 6.0370994, 7.533837 , 8.083211 ,
        7.825903 , 8.588028 , 5.9410152, 7.6885796],
       [6.5942616, 6.7096944, 5.005406 , 5.0034885, 5.705789 , 6.4748473,
        7.0696425, 7.2804337, 5.74439  , 6.703559 ]], dtype=float32)>