In [2]:
import pandas as pd

In [23]:
df = pd.DataFrame({'col1': [1.0,2.0,3.1,3.2], #float
                   'col2': [1,2,3,4], #cate
                   })

In [29]:
df.dtypes

col1    float64
col2      int64
dtype: object

In [31]:
df.select_dtypes('int64')

col1  col2
0   NaN     0
1   NaN     0
2   NaN     0
3   NaN     0

In [1]:
import torch

In [2]:
torch.zeros(3)

tensor([0., 0., 0.])

In [3]:
classes = 3


In [5]:
torch.ones(classes)/classes

tensor([0.3333, 0.3333, 0.3333])

In [5]:
from pyro import distributions as dist
import torch
import pyro

In [6]:
v=torch.Tensor([1/3,1/3,1/3])
v

tensor([0.3333, 0.3333, 0.3333])

In [7]:
pyro.sample('test',dist.Multinomial(v))

NotImplementedError: inhomogeneous total_count is not supported

In [16]:
import torch
classes = 5
feature = 4

In [18]:
torch.ones(classes,feature)/feature

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

In [ ]:
test = {'w-education': {'probability': tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]]}}

In [1]:
l = []
x = torch.tensor([1,2,3])

NameError: name 'torch' is not defined